# Generated by Django 5.2.4 on 2025-09-16 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items_table',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='food_items_table',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order_main_table',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order_sub_table',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='cart', max_length=200)),
                ('total_amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ORDERSUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order_sub_table')),
            ],
        ),
    ]
