# Generated by Django 5.2.4 on 2025-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_food_items_table_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_table',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
